# Generated by Django 5.1.5 on 2025-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('level', models.CharField(max_length=10)),
                ('delFlg', models.CharField(max_length=10)),
                ('compFlg', models.CharField(max_length=10)),
            ],
        ),
    ]
